$$DYN:ID3:NOCACHE:FULL$$
$$E:ID3:NOCACHEFIN$$
$$CONTENT:TOJS$$
$$E:AUTH:CHECK_LOGIN:~authrequiredlevel:LOOSE$$
$$B:IMMOBC:AGENCEPUBLICATIONSESSION$$
$$E:IMMOBC:AGENCECORE:QRY:IDAGENCE$$
$$BIF:IMMOBC:AGENCEPUBLICATIONSESSION$$
$$DO:1:100$$
$$IF:IMMOBC:AGENCEPUBLICATIONSESSION:BOU1NUM$$
	$$IF=:0:IMMOBC:AGENCEPUBLICATIONSESSION:SI_CACHE$$ 
		$$IF0:IMMOBC:AGENCEPUBLICATIONSESSION:SI_VEILLE$$ 
			$$IF=:1$2:IMMOBC:AGENCEPUBLICATIONSESSION:IDTYPEPARUTION$$ 
				$$IF=:0:IMMOBC:AGENCEPUBLICATIONSESSION:SI_FIGEE$$
					<br />
					<a href="javascript:openext('http://annonces.selogerpro.com/$$IMMOBC:AGENCEPUBLICATIONSESSION:IDPUBLICATION$$/$$IMMOBC:AGENCEPUBLICATIONSESSION:IDAGENCE$$/p_figerpub.htm?publication=$$IMMOBC:AGENCEPUBLICATIONSESSION:PUBLICATION urlencode$$&anntot=$$IMMOBC:AGENCECORE:NBANN$$','BlocagePublication',400,400,'no');">Figer la publication $$IMMOBC:AGENCEPUBLICATIONSESSION:PUBLICATION$$</a>
				$$END:SIPASDEJAFIGE$$ 
			$$END:SIVEILLE$$ 
		$$END:IDTYPEPARUTION$$ 
	$$END:CACHE$$
$$END$$
$$LOOP$$
$$BFIN$$