$$E:ID3:NOUACACHE$$ 
$$E:ID3:NOCACHE$$
$$CONTENT:TOJS$$
$$REM$$
	$$A:XDOM=@@FORM:XDOM@@$$
	$$A:ID3DOM=@@FORM:ID3DOM@@$$
$$END$$
$$INCL:CFG.HTM$$
$$E:E3:CAT:QRY:CAT:SLPRO$$
$$A:APPELEXTERIEUR=1$$
$$INCL:HAUT_BASE.HTM$$

$$IF:FORM:ACTIVE$$
$$E:SLPRO:WEBVISIUM_ACTIVE:~active:QRY:ACTIVE:~refwv:QRY:REFWV:~idannonce:QRY:IDANNONCE$$ 

$$END$$