$$NOPECR$$$$DYN:ID3:NOCNXWEB$$$$DYN:ID3:NOCYBERMONITOR$$$$DYN:ID3:NOCACHE$$$$DYN:ID3:NOFOOTER$$$$DYN:ID3:CONTENTTYPE:Text/XML$$$$B:SLPRO:FLASHAGENCEANNONCES:~idtiers:REP:1$$$$SLPRO:FLASHAGENCEANNONCES:~idtiers:ERROR$$
<root>
	<annonces>$$BIF:SLPRO:FLASHAGENCEANNONCES:~idtiers$$$$DO:1:999$$
		<annonce>
			<agences>$$SLPRO:FLASHAGENCEANNONCES:~idtiers:IDAGS$$</agences>
			<image1><![CDATA[$$SLPRO:FLASHAGENCEANNONCES:~idtiers:PHOTO1$$]]></image1>
			<image2><![CDATA[$$SLPRO:FLASHAGENCEANNONCES:~idtiers:PHOTO2$$]]></image2>
			<image3><![CDATA[$$SLPRO:FLASHAGENCEANNONCES:~idtiers:PHOTO3$$]]></image3>
			<no>$$IF:SLPRO:FLASHAGENCEANNONCES:~idtiers:REFANNONCE$$$$SLPRO:FLASHAGENCEANNONCES:~idtiers:REFANNONCE$$$$END$$$$IF0:SLPRO:FLASHAGENCEANNONCES:~idtiers:REFANNONCE$$$$SLPRO:FLASHAGENCEANNONCES:~idtiers:IDANNONCE$$$$END$$</no>
			<prix>$$SLPRO:FLASHAGENCEANNONCES:~idtiers:PRIX$$</prix>
			<honoraires>$$SLPRO:FLASHAGENCEANNONCES:~idtiers:HONORAIRES$$</honoraires>
			<loyer_hc>$$SLPRO:FLASHAGENCEANNONCES:~idtiers:LOYERHC$$</loyer_hc>
			<loyer_cc>$$SLPRO:FLASHAGENCEANNONCES:~idtiers:LOYERCC$$</loyer_cc>
			<texte><![CDATA[$$SLPRO:FLASHAGENCEANNONCES:~idtiers:DESCRIPTIF_FR$$]]></texte>
			<localisation><![CDATA[$$SLPRO:FLASHAGENCEANNONCES:~idtiers:VILLE$$]]></localisation>
			<nom_agence><![CDATA[$$SLPRO:FLASHAGENCEANNONCES:~idtiers:NOM$$]]></nom_agence>
			<tel_contact><![CDATA[$$SLPRO:FLASHAGENCEANNONCES:~idtiers:TELEPHONE$$]]></tel_contact>
			<nom_contact><![CDATA[$$SLPRO:FLASHAGENCEANNONCES:~idtiers:CONTACT$$]]></nom_contact>
			<bandeau><![CDATA[$$SLPRO:FLASHAGENCEANNONCES:~idtiers:BANDEAU$$]]></bandeau>
			<dossier><![CDATA[$$SLPRO:FLASHAGENCEANNONCES:~idtiers:REFANNONCE$$]]></dossier>
			<mandat><![CDATA[$$SLPRO:FLASHAGENCEANNONCES:~idtiers:NUMERO_MANDAT$$]]></mandat>
			<typeoffre><![CDATA[$$SLPRO:FLASHAGENCEANNONCES:~idtiers:LIBELLE_FR$$]]></typeoffre>
			<photo>$$SLPRO:FLASHAGENCEANNONCES:~idtiers:PHOTOS$$</photo>
		</annonce>$$LOOP$$$$BFIN$$
	</annonces>
</root>

