$$CONTENT:TOJS$$
$$DYN:ID3:NOFOOTER$$
$$DYN:ID3:NOCNXWEB$$
$$E:XEDY:CAT:159927$$
$$E:XEDY:CAT_POSITION:159927:ALIAS:CAT$$
<!--#include virtual="incl_var_env.htm" -->
$$B:XEDY:PATH:VAL:XEDY_CAT_CAT*ID:ALIAS:NAVIGATION$$
		$$E:XEDY:CAT_POSITION:VAL:XEDY_CAT_CAT*ID:ALIAS:CAT$$
		$$E:XEDY:CAT:VAL:CAT_2:ALIAS:CATLIBELLE$$
		$$A:XEDYCATID=@@XEDY:CAT:CAT_ID@@$$
                
		$$A:PAGEXEDY=@@XEDY:CAT:CAT_ID@@$$
	


$$INCL:BAS.HTM$$