$$TTL:1440$$$$DYN:ID3:TOJS$$
$$B:IMMOBW:PAYS:TT:QRY:IDTT$$$$BIF:IMMOBW:PAYS:TT$$$$IF+:2:IMMOBW:PAYS:TT:NBR$$
<TR>
	<TD COLSPAN="2" VALIGN="TOP" WIDTH="80%">&nbsp;</TD>
</TR>
<TR>
	<TD COLSPAN="2" VALIGN="TOP" WIDTH="80%"><FONT FACE="Verdana, Arial, Helvetica, sans-serif" SIZE="2">
		<B><FONT COLOR="#B91313">Pays: </FONT></B>&nbsp;
		<SELECT NAME="idpays">$$DO:1:999$$
		<OPTION VALUE="$$IMMOBW:PAYS:TT:IDPAYS$$"$$IF=:250:IMMOBW:PAYS:TT:IDPAYS$$ SELECTED$$END$$>$$IMMOBW:PAYS:TT:PAYS_FR$$$$LOOP$$
		</SELECT>
	</FONT></TD>
</TR>$$END$$$$BFIN$$
