$$DYN:ID3:TOJS$$$$E:ID3:NOUACACHE$$
$$INCL:DICO-FORM.HTM$$
<!--$$FORM:LANG$$-->

$$E:IMMOBW:PANIER:NBANN$$
$$IF:IMMOBW:PANIER:NBANN$$
<A href="/recherche.htm?lang=$$LANGUE$$">
<B><U>$$LG:VOIRPAN$$<br>
($$IMMOBW:PANIER:NBANN$$ $$LG:ANNONCE$$$$IF=:FR:LANGUE$$$$IMMOBW:PANIER:NBANN pluriel$$$$END:LANGUE$$ $$LG:SELEC$$$$IF=:FR:LANGUE$$$$IMMOBW:PANIER:NBANN pluriel$$$$END:LANGUE$$)
</U></B></A>
$$END$$